### ISSUE TITLE
如何安装？

### ISSUE THREAD

**Issue by iole05dix** [vvipi/py3_demo_on_vnpy_ctp#1]
利用原有的vnpy环境？基于vnpy 哪个版本？

**Comment by iole05dix** [comment]
按这个

> 
> 修改user.json中的模拟账号。
> 
> 修改basesetting中的工作目录WORKING_DIR为你的工作目录。
> 
> 启动demoMain.py


修改不行. 
出错信息


> Traceback (most recent call last):
>   File "demoMain.py", line 12, in <module>
>     from modules.ctpApi import *
>   File "/home/*/py3_demo_on_vnpy_ctp/py3_ctp_demo_on_vnpy/modules/ctpApi.py", line 5, in <module>
>     from modules.vnctpmd import MdApi
> ImportError: No module named vnctpmd

**Comment by ufo007ufo009** [comment]
你好，方便留个QQ吗，下载后运行出错

**Comment by vvipi** [comment]
> 利用原有的vnpy环境？基于vnpy 哪个版本？

版本无所谓，只用了CTPAPI，也就是`thostmduserapi_se.dll` `thosttraderapi_se.dll` `vnctpmd.pyd` `vnctptd.pyd`四个文件。

**Comment by vvipi** [comment]
> 按这个
> 
> > 修改user.json中的模拟账号。
> > 修改basesetting中的工作目录WORKING_DIR为你的工作目录。
> > 启动demoMain.py
> 
> 修改不行.
> 出错信息
> 
> > Traceback (most recent call last):
> > File "demoMain.py", line 12, in 
> > from modules.ctpApi import *
> > File "/home/*/py3_demo_on_vnpy_ctp/py3_ctp_demo_on_vnpy/modules/ctpApi.py", line 5, in 
> > from modules.vnctpmd import MdApi
> > ImportError: No module named vnctpmd

确保是64位版本windows7或windows10，python3.7
确保有vnctpmd.pyd这个文件
